### PR TITLE
[WIP] Authentication with Devise

### PR DESCRIPTION
**Pull request by nixpulvis**
Move authentication logic to the devise gem. This gem is tried and true.
### To Do
- [ ] Add back in password auth option.
- [ ] Fix tests.
- [ ] UI cleanup.
### Open Questions
- Migrations strategy for existing applications.
- LDAP security and password requirements.

### CODE REVIEW

**Comment by nixpulvis** [comment]
Any thoughts on this before I continue?

**Comment by NatTuck** [comment]
That looks like a pretty reasonable changeset for moving to devise.

We should probably keep the "set your name" prompt on login somehow.

**Comment by nixpulvis** [comment]
Wow I hate how GitHub doesn't warn you about deleting branches with open PRs.

**Comment by NatTuck** [comment]
This would be better if travis was green instead of red.

**Pull request closed without merging**
